/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

/**
 *
 * @author ChaVaZaSRL
 */
public class Pemilihan_Dokter extends javax.swing.JFrame {

    /**
     * Creates new form Pemilihan_Dokter
     */
    public Pemilihan_Dokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Pilih = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Spesialist = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Usia = new javax.swing.JTextField();
        Jenis = new javax.swing.JTextField();
        Gol = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        Warga = new javax.swing.JTextField();
        Waktu = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 40, 190, 28);

        jLabel2.setText("Pilih Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 60, 14);

        Pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "DR. Farras Yassar", "DR. Dian Sikahita", "DR. Harun Ulum Fajar" }));
        Pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihActionPerformed(evt);
            }
        });
        getContentPane().add(Pilih);
        Pilih.setBounds(100, 90, 190, 20);

        jLabel3.setText("Dokter Spesialis");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 470, 90, 14);

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 150, 70, 14);

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 190, 70, 14);

        jLabel6.setText("Usia");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 230, 70, 14);

        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 270, 70, 14);

        jLabel8.setText("Golongan Darah");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 310, 90, 14);

        jLabel9.setText("Status");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 350, 90, 14);

        jLabel10.setText("Kewarganegaraan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 390, 90, 14);

        jLabel11.setText("Waktu Praktek");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 430, 90, 14);
        getContentPane().add(Spesialist);
        Spesialist.setBounds(160, 470, 140, 30);
        getContentPane().add(Nama);
        Nama.setBounds(160, 150, 140, 30);
        getContentPane().add(Alamat);
        Alamat.setBounds(160, 190, 140, 30);
        getContentPane().add(Usia);
        Usia.setBounds(160, 230, 140, 30);
        getContentPane().add(Jenis);
        Jenis.setBounds(160, 270, 140, 30);
        getContentPane().add(Gol);
        Gol.setBounds(160, 310, 140, 30);
        getContentPane().add(Status);
        Status.setBounds(160, 350, 140, 30);
        getContentPane().add(Warga);
        Warga.setBounds(160, 390, 140, 30);
        getContentPane().add(Waktu);
        Waktu.setBounds(160, 430, 140, 30);

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(20, 120, 310, 400);

        setBounds(0, 0, 416, 564);
    }// </editor-fold>//GEN-END:initComponents

    private void PilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihActionPerformed
        if(Pilih.getSelectedItem().equals("DR. Farras Yassar")){
            Nama.setText("DR. Farras Yassar ");
            Alamat.setText("Jl. Surabaya 16, Malang");
            Usia.setText("20 Tahun");
            Jenis.setText("Laki-Laki");
            Gol.setText("A");
            Status.setText("Belum Menikah ");
            Warga.setText("Indonesia");
            Spesialist.setText("Dokter Umum");
            Waktu.setText(" Pagi (07.00-15.00)");
        }
        else if(Pilih.getSelectedItem().equals("DR. Dian Sikahita")){
            Nama.setText("DR. Dian Sikahita");
            Alamat.setText("Jl. Veteran 3, Malang");
            Usia.setText("20 Tahun");
            Jenis.setText("Perempuan");
            Gol.setText("O");
            Status.setText("Belum Menikah");
            Warga.setText("Indonesia");
            Spesialist.setText("Dokter Gigi");
            Waktu.setText(" Sore (16.00-22.00)");
        }
        else if(Pilih.getSelectedItem().equals("DR. Harun Ulum Fajar")){
            Nama.setText("DR. Harun Ulum Fajar");
            Alamat.setText("Jl. Bandung 9, Malang");
            Usia.setText("20 Tahun");
            Jenis.setText("Laki-Laki");
            Gol.setText("B");
            Status.setText("Belum Menikah");
            Warga.setText("Indonesia");
            Spesialist.setText("Dokter Gizi");
            Waktu.setText(" Malam (22.00-06.00)");

        }
    }//GEN-LAST:event_PilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemilihan_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemilihan_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemilihan_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemilihan_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemilihan_Dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Gol;
    private javax.swing.JTextField Jenis;
    private javax.swing.JTextField Nama;
    private javax.swing.JComboBox<String> Pilih;
    private javax.swing.JTextField Spesialist;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField Usia;
    private javax.swing.JTextField Waktu;
    private javax.swing.JTextField Warga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
