/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

/**
 *
 * @author ChaVaZaSRL
 */
public class Program_Aritmetika extends javax.swing.JFrame {
    String jns = "";
    int jml;
    /**
     * Creates new form Program_Aritmetika
     */
    public Program_Aritmetika() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        b2 = new javax.swing.JTextField();
        bil1 = new javax.swing.JLabel();
        b3 = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        b4 = new javax.swing.JTextField();
        bil4 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        pilihanbil = new javax.swing.JComboBox<>();
        panel = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Program Aritmetika");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 220, 70);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel2.setText("Jenis Aritmetika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 80, 20);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(250, 90, 130, 20);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 380, 110, 30);
        getContentPane().add(b2);
        b2.setBounds(170, 260, 130, 30);

        bil1.setText("Bilangan 1");
        getContentPane().add(bil1);
        bil1.setBounds(60, 220, 90, 14);
        getContentPane().add(b3);
        b3.setBounds(170, 300, 130, 30);

        hasil.setEditable(false);
        getContentPane().add(hasil);
        hasil.setBounds(160, 420, 150, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Penjumlahan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 140, 130, 40);

        bil3.setText("Bilangan 3");
        getContentPane().add(bil3);
        bil3.setBounds(60, 300, 90, 14);

        jLabel5.setText("Jumlah Bilangan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 190, 90, 14);

        bil2.setText("Bilangan 2");
        getContentPane().add(bil2);
        bil2.setBounds(60, 260, 90, 14);
        getContentPane().add(b4);
        b4.setBounds(170, 340, 130, 30);

        bil4.setText("Bilangan 4");
        getContentPane().add(bil4);
        bil4.setBounds(60, 340, 90, 14);
        getContentPane().add(b1);
        b1.setBounds(170, 220, 130, 30);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        getContentPane().add(pilihanbil);
        pilihanbil.setBounds(170, 190, 130, 20);

        panel.setBackground(new java.awt.Color(0, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setRollover(true);
        getContentPane().add(panel);
        panel.setBounds(30, 140, 350, 370);

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 540);

        setBounds(0, 0, 447, 573);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b1.getText().toString());
        a3 = Double.parseDouble(b1.getText().toString());
        a4 = Double.parseDouble(b1.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1+a2;
                hasil.setText(""+a1+" + "+a2+" = "+hsl);
            }
            if(jml == 3){
                hsl = a1+a2+a3;
                hasil.setText(""+a1+" + "+a2+" + "+a3+" = "+hsl);
            }
            if(jml == 4){
                hsl = a1+a2+a3+a4;
                hasil.setText(""+a1+" + "+a2+" + "+a3+" + "+a4+" = "+hsl);
            }
        }
        else if(jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1-a2;
                hasil.setText(""+a1+" - "+a2+" = "+hsl);
            }
            if(jml == 3){
                hsl = a1-a2-a3;
                hasil.setText(""+a1+" - "+a2+" - "+a3+" = "+hsl);
            }
            if(jml == 4){
                hsl = a1+a2+a3+a4;
                hasil.setText(""+a1+" - "+a2+" - "+a3+" - "+a4+" = "+hsl);
            }
        }
        if(jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1+a2;
                hasil.setText(""+a1+" x "+a2+" = "+hsl);
            }
            if(jml == 3){
                hsl = a1+a2+a3;
                hasil.setText(""+a1+" x "+a2+" x "+a3+" = "+hsl);
            }
            if(jml == 4){
                hsl = a1+a2+a3+a4;
                hasil.setText(""+a1+" x "+a2+" x "+a3+" x "+a4+" = "+hsl);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void getJumlah(){
        if(pilihanbil.getSelectedItem().equals("2")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
        }
        else if(pilihanbil.getSelectedItem().equals("3")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
        }
        else if(pilihanbil.getSelectedItem().equals("4")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
        }
    }
    
    public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            jLabel3.setText("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            jLabel3.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            jLabel3.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program_Aritmetika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program_Aritmetika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program_Aritmetika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program_Aritmetika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program_Aritmetika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JToolBar panel;
    private javax.swing.JComboBox<String> pilihanbil;
    // End of variables declaration//GEN-END:variables
}
